Repository Team-PalPalHae-Dealight/Team-PalPalHae-Dealight-BE, pull requests merged in 2023-11, with the labels that each got.

#54 고객 정보 수정 API 구현
  src/docs/asciidoc/member.adoc
  src/main/java/com/palpal/dealightbe/domain/address/application/dto/request/AddressReq.java
  src/main/java/com/palpal/dealightbe/domain/address/domain/Address.java
  src/main/java/com/palpal/dealightbe/domain/member/application/MemberService.java
  src/main/java/com/palpal/dealightbe/domain/member/application/dto/request/MemberUpdateReq.java
  src/main/java/com/palpal/dealightbe/domain/member/application/dto/response/MemberUpdateRes.java
  src/main/java/com/palpal/dealightbe/domain/member/domain/Member.java
  src/main/java/com/palpal/dealightbe/domain/member/presentation/MemberController.java
  src/test/java/com/palpal/dealightbe/domain/member/application/MemberServiceTest.java
  src/test/java/com/palpal/dealightbe/domain/member/presentation/MemberControllerTest.java
Labels: 첫번째 스프린트, 💡 feature

#57 상품 삭제 API 구현
  src/docs/asciidoc/Item.adoc
  src/main/java/com/palpal/dealightbe/domain/item/application/ItemService.java
  src/main/java/com/palpal/dealightbe/domain/item/domain/Item.java
  src/main/java/com/palpal/dealightbe/domain/item/domain/ItemRepository.java
  src/main/java/com/palpal/dealightbe/domain/item/presentation/ItemController.java
  src/main/java/com/palpal/dealightbe/global/error/ErrorCode.java
  src/test/java/com/palpal/dealightbe/domain/item/application/ItemServiceTest.java
  src/test/java/com/palpal/dealightbe/domain/item/presentation/ItemControllerTest.java
  src/test/java/com/palpal/dealightbe/domain/order/presentation/OrderControllerTest.java
Labels: 첫번째 스프린트, 💡 feature

#68 hotfix: MemberService 애너테이션 수정
  src/main/java/com/palpal/dealightbe/domain/member/application/MemberService.java
Labels: 🚨 hotfix, 두번째 스프린트

#61 JwtAuthenticationFilter 및 필요한 클래스 구현, 인증객체로부터 ProviderId 값을 추출하는 AOP 구현
  src/main/java/com/palpal/dealightbe/config/SecurityConfig.java
  src/main/java/com/palpal/dealightbe/config/WebMvcConfig.java
  src/main/java/com/palpal/dealightbe/domain/auth/application/AuthService.java
  src/main/java/com/palpal/dealightbe/domain/auth/domain/Jwt.java
  src/main/java/com/palpal/dealightbe/domain/auth/domain/JwtAuthentication.java
  src/main/java/com/palpal/dealightbe/domain/auth/domain/JwtAuthenticationToken.java
  src/main/java/com/palpal/dealightbe/domain/auth/filter/JwtAuthenticationFilter.java
  src/main/java/com/palpal/dealightbe/domain/auth/presentation/CustomAuthAccessDeniedHandler.java
  src/main/java/com/palpal/dealightbe/domain/member/domain/Member.java
  src/main/java/com/palpal/dealightbe/domain/member/domain/RoleType.java
  src/main/java/com/palpal/dealightbe/global/aop/ProviderId.java
  src/main/java/com/palpal/dealightbe/global/aop/ProviderIdAop.java
  src/main/java/com/palpal/dealightbe/global/error/ErrorCode.java
  src/main/resources/logback.xml
  src/test/java/com/palpal/dealightbe/domain/auth/application/AuthServiceTest.java
  src/test/java/com/palpal/dealightbe/domain/auth/domain/JwtTest.java
  src/test/java/com/palpal/dealightbe/domain/item/presentation/ItemControllerTest.java
  src/test/java/com/palpal/dealightbe/domain/member/presentation/MemberControllerTest.java
  src/test/java/com/palpal/dealightbe/domain/order/presentation/OrderControllerTest.java
  src/test/java/com/palpal/dealightbe/domain/store/presentation/StoreControllerTest.java
Labels: 첫번째 스프린트, 💡 feature

#66 가게 영업 상태 변경 API
  src/docs/asciidoc/Store.adoc
  src/main/java/com/palpal/dealightbe/domain/store/application/StoreService.java
  src/main/java/com/palpal/dealightbe/domain/store/application/dto/request/StoreCreateReq.java
  src/main/java/com/palpal/dealightbe/domain/store/application/dto/request/StoreStatusReq.java
  src/main/java/com/palpal/dealightbe/domain/store/application/dto/response/StoreStatusUpdateRes.java
  src/main/java/com/palpal/dealightbe/domain/store/domain/Store.java
  src/main/java/com/palpal/dealightbe/domain/store/domain/StoreStatus.java
  src/main/java/com/palpal/dealightbe/domain/store/presentation/StoreController.java
  src/main/java/com/palpal/dealightbe/global/error/ErrorCode.java
  src/test/java/com/palpal/dealightbe/domain/store/application/StoreServiceTest.java
  src/test/java/com/palpal/dealightbe/domain/store/presentation/StoreControllerTest.java
Labels: 첫번째 스프린트, 💡 feature

#69 hotfix: Item.adoc 내용 수정
  src/docs/asciidoc/Item.adoc
Labels: 🚨 hotfix, 두번째 스프린트

#70 상품 상세 정보 조회(단건) API 구현
  src/docs/asciidoc/Item.adoc
  src/main/java/com/palpal/dealightbe/domain/item/application/ItemService.java
  src/main/java/com/palpal/dealightbe/domain/item/domain/ItemRepository.java
  src/main/java/com/palpal/dealightbe/domain/item/presentation/ItemController.java
  src/test/java/com/palpal/dealightbe/domain/item/application/ItemServiceTest.java
  src/test/java/com/palpal/dealightbe/domain/item/presentation/ItemControllerTest.java
Labels: 💡 feature, 두번째 스프린트

#73 업체 이미지 등록 API
  src/docs/asciidoc/Store.adoc
  src/main/java/com/palpal/dealightbe/domain/image/application/dto/request/ImageUploadReq.java
  src/main/java/com/palpal/dealightbe/domain/image/application/dto/response/ImageRes.java
  src/main/java/com/palpal/dealightbe/domain/store/application/StoreService.java
  src/main/java/com/palpal/dealightbe/domain/store/presentation/StoreController.java
  src/test/java/com/palpal/dealightbe/domain/store/application/StoreServiceTest.java
  src/test/java/com/palpal/dealightbe/domain/store/presentation/StoreControllerTest.java
Labels: 💡 feature, 두번째 스프린트

#77 고객 프로필 이미지 수정 API
  src/docs/asciidoc/member.adoc
  src/main/java/com/palpal/dealightbe/domain/address/application/dto/request/AddressReq.java
  src/main/java/com/palpal/dealightbe/domain/address/domain/Address.java
  src/main/java/com/palpal/dealightbe/domain/image/dto/request/ImageUploadReq.java
  src/main/java/com/palpal/dealightbe/domain/image/dto/response/ImageRes.java
  src/main/java/com/palpal/dealightbe/domain/member/application/MemberService.java
  src/main/java/com/palpal/dealightbe/domain/member/application/dto/request/MemberUpdateReq.java
  src/main/java/com/palpal/dealightbe/domain/member/domain/Member.java
  src/main/java/com/palpal/dealightbe/domain/member/presentation/MemberController.java
  src/test/java/com/palpal/dealightbe/domain/member/application/MemberServiceTest.java
  src/test/java/com/palpal/dealightbe/domain/member/presentation/MemberControllerTest.java
Labels: 💡 feature, 두번째 스프린트

#81 업체 영업 상태 조회 API
  src/docs/asciidoc/Store.adoc
  src/main/java/com/palpal/dealightbe/domain/store/application/StoreService.java
  src/main/java/com/palpal/dealightbe/domain/store/application/dto/response/StoreStatusRes.java
  src/main/java/com/palpal/dealightbe/domain/store/presentation/StoreController.java
  src/test/java/com/palpal/dealightbe/domain/store/application/StoreServiceTest.java
  src/test/java/com/palpal/dealightbe/domain/store/presentation/StoreControllerTest.java
Labels: 💡 feature, 두번째 스프린트

#83 업체 등록시 기본 이미지 등록
  src/main/java/com/palpal/dealightbe/domain/store/application/StoreService.java
  src/main/java/com/palpal/dealightbe/domain/store/application/dto/request/StoreCreateReq.java
  src/main/java/com/palpal/dealightbe/domain/store/application/dto/response/StoreCreateRes.java
  src/test/java/com/palpal/dealightbe/domain/store/application/StoreServiceTest.java
  src/test/java/com/palpal/dealightbe/domain/store/presentation/StoreControllerTest.java
Labels: 💡 feature

#84 회원가입 및 로그인 플로우에 따른 메시지 반환
  build.gradle
  src/docs/asciidoc/Auth.adoc
  src/main/java/com/palpal/dealightbe/config/SecurityConfig.java
  src/main/java/com/palpal/dealightbe/domain/address/domain/Address.java
  src/main/java/com/palpal/dealightbe/domain/auth/application/AuthService.java
  src/main/java/com/palpal/dealightbe/domain/auth/application/dto/request/MemberSignupReq.java
  src/main/java/com/palpal/dealightbe/domain/auth/application/dto/response/JoinRequireRes.java
  src/main/java/com/palpal/dealightbe/domain/auth/application/dto/response/LoginRes.java
  src/main/java/com/palpal/dealightbe/domain/auth/application/dto/response/MemberSignupRes.java
  src/main/java/com/palpal/dealightbe/domain/auth/filter/JwtAuthenticationFilter.java
  src/main/java/com/palpal/dealightbe/domain/auth/infra/AuthRepository.java
  src/main/java/com/palpal/dealightbe/domain/auth/presentation/AuthController.java
  src/main/java/com/palpal/dealightbe/domain/auth/presentation/CustomOAuth2AuthenticationSuccessHandler.java
  src/main/java/com/palpal/dealightbe/domain/member/domain/Member.java
  src/main/java/com/palpal/dealightbe/domain/member/domain/MemberRepository.java
  src/main/java/com/palpal/dealightbe/domain/member/domain/MemberRole.java
  src/main/java/com/palpal/dealightbe/domain/member/domain/MemberRoleRepository.java
  src/main/java/com/palpal/dealightbe/domain/member/domain/Role.java
  src/main/java/com/palpal/dealightbe/domain/member/domain/RoleRepository.java
  src/main/java/com/palpal/dealightbe/domain/member/domain/RoleType.java
  src/main/java/com/palpal/dealightbe/global/error/ErrorCode.java
  src/main/java/com/palpal/dealightbe/global/error/GlobalExceptionHandler.java
  src/main/resources/application.yml
  src/test/java/com/palpal/dealightbe/domain/auth/application/AuthServiceTest.java
  src/test/java/com/palpal/dealightbe/domain/auth/domain/JwtTest.java
  src/test/java/com/palpal/dealightbe/domain/auth/presentation/AuthControllerTest.java
Labels: 🐞 bug, 💡 feature, 두번째 스프린트

#80 상품 목록 조회(업체 시점) API 구현
  src/docs/asciidoc/Item.adoc
  src/main/java/com/palpal/dealightbe/config/JpaConfig.java
  src/main/java/com/palpal/dealightbe/domain/item/application/ItemService.java
  src/main/java/com/palpal/dealightbe/domain/item/application/dto/response/ItemsRes.java
  src/main/java/com/palpal/dealightbe/domain/item/domain/ItemRepository.java
  src/main/java/com/palpal/dealightbe/domain/item/domain/ItemRepositoryCustom.java
  src/main/java/com/palpal/dealightbe/domain/item/infrastructure/ItemRepositoryImpl.java
  src/main/java/com/palpal/dealightbe/domain/item/presentation/ItemController.java
  src/test/java/com/palpal/dealightbe/domain/item/application/ItemServiceTest.java
  src/test/java/com/palpal/dealightbe/domain/item/presentation/ItemControllerTest.java
Labels: 💡 feature, 두번째 스프린트

#86 hotfix: ItemServiceTest itemFindAllForStoreSuccessTest 메서드 수정
  src/test/java/com/palpal/dealightbe/domain/item/application/ItemServiceTest.java
Labels: 🚨 hotfix, 두번째 스프린트

#78 주문 상세 내용 조회
  src/docs/asciidoc/Order.adoc
  src/main/java/com/palpal/dealightbe/domain/order/application/OrderService.java
  src/main/java/com/palpal/dealightbe/domain/order/domain/Order.java
  src/main/java/com/palpal/dealightbe/domain/order/presentation/OrderController.java
  src/main/java/com/palpal/dealightbe/global/error/ErrorCode.java
  src/test/java/com/palpal/dealightbe/domain/order/presentation/OrderControllerTest.java
Labels: 💡 feature, 두번째 스프린트

#87 업체 이미지 수정 API
  src/docs/asciidoc/Store.adoc
  src/main/java/com/palpal/dealightbe/domain/store/application/StoreService.java
  src/main/java/com/palpal/dealightbe/domain/store/presentation/StoreController.java
  src/test/java/com/palpal/dealightbe/domain/store/application/StoreServiceTest.java
  src/test/java/com/palpal/dealightbe/domain/store/presentation/StoreControllerTest.java
Labels: 💡 feature, 두번째 스프린트

#92 hotfix : test 코드 수정
  src/test/java/com/palpal/dealightbe/domain/order/application/OrderServiceTest.java
Labels: 🐞 bug

#91 고객 프로필 이미지 삭제 API
  src/docs/asciidoc/member.adoc
  src/main/java/com/palpal/dealightbe/domain/member/application/MemberService.java
  src/main/java/com/palpal/dealightbe/domain/member/presentation/MemberController.java
  src/main/java/com/palpal/dealightbe/global/error/ErrorCode.java
  src/test/java/com/palpal/dealightbe/domain/member/application/MemberServiceTest.java
  src/test/java/com/palpal/dealightbe/domain/member/presentation/MemberControllerTest.java
Labels: 💡 feature, 두번째 스프린트

#99 헤더의 Authorization이 null인 경우 로그인 요청, 회원가입시 기본 위치 기본값으로 수정
  src/main/java/com/palpal/dealightbe/domain/address/domain/Address.java
  src/main/java/com/palpal/dealightbe/domain/auth/application/AuthService.java
  src/main/java/com/palpal/dealightbe/domain/auth/filter/JwtAuthenticationFilter.java
  src/main/java/com/palpal/dealightbe/domain/auth/presentation/AuthController.java
  src/main/java/com/palpal/dealightbe/domain/auth/presentation/CustomOAuth2AuthenticationSuccessHandler.java
Labels: 🐞 bug, 두번째 스프린트

#101 업체 이미지 삭제 API
  src/docs/asciidoc/Store.adoc
  src/main/java/com/palpal/dealightbe/domain/auth/application/dto/request/MemberSignupReq.java
  src/main/java/com/palpal/dealightbe/domain/store/application/StoreService.java
  src/main/java/com/palpal/dealightbe/domain/store/presentation/StoreController.java
  src/main/java/com/palpal/dealightbe/global/error/ErrorCode.java
  src/test/java/com/palpal/dealightbe/domain/store/presentation/StoreControllerTest.java
Labels: 💡 feature, 두번째 스프린트, 🛠️ refactoring

#106 업체 서비스 테스트 코드 변경 사항 반영
  src/docs/asciidoc/Store.adoc
  src/test/java/com/palpal/dealightbe/domain/store/application/StoreServiceTest.java
Labels: 🚨 hotfix, 두번째 스프린트

#93 리뷰 등록
  build.gradle
  src/docs/asciidoc/Store.adoc
  src/docs/asciidoc/member.adoc
  src/main/java/com/palpal/dealightbe/config/SecurityConfig.java
  src/main/java/com/palpal/dealightbe/domain/address/domain/Address.java
  src/main/java/com/palpal/dealightbe/domain/auth/application/AuthService.java
  src/main/java/com/palpal/dealightbe/domain/auth/application/dto/request/MemberSignupReq.java
  src/main/java/com/palpal/dealightbe/domain/auth/filter/JwtAuthenticationFilter.java
  src/main/java/com/palpal/dealightbe/domain/auth/presentation/AuthController.java
  src/main/java/com/palpal/dealightbe/domain/auth/presentation/CustomOAuth2AuthenticationSuccessHandler.java
  src/main/java/com/palpal/dealightbe/domain/member/application/MemberService.java
  src/main/java/com/palpal/dealightbe/domain/member/presentation/MemberController.java
  src/main/java/com/palpal/dealightbe/domain/store/application/StoreService.java
  src/main/java/com/palpal/dealightbe/domain/store/presentation/StoreController.java
  src/main/java/com/palpal/dealightbe/global/error/ErrorCode.java
  src/main/resources/application.yml
  src/main/resources/data.sql
  src/test/java/com/palpal/dealightbe/domain/member/application/MemberServiceTest.java
  src/test/java/com/palpal/dealightbe/domain/member/presentation/MemberControllerTest.java
  src/test/java/com/palpal/dealightbe/domain/store/application/StoreServiceTest.java
  src/test/java/com/palpal/dealightbe/domain/store/presentation/StoreControllerTest.java
Labels: 💡 feature, 두번째 스프린트

#95 상품 목록 조회(고객 시점) API 구현
  src/docs/asciidoc/Item.adoc
  src/main/java/com/palpal/dealightbe/domain/item/application/ItemService.java
  src/main/java/com/palpal/dealightbe/domain/item/domain/ItemRepository.java
  src/main/java/com/palpal/dealightbe/domain/item/domain/ItemSortType.java
  src/main/java/com/palpal/dealightbe/domain/item/presentation/ItemController.java
  src/main/java/com/palpal/dealightbe/global/error/ErrorCode.java
  src/test/java/com/palpal/dealightbe/domain/item/application/ItemServiceTest.java
  src/test/java/com/palpal/dealightbe/domain/item/presentation/ItemControllerTest.java
Labels: 💡 feature, 두번째 스프린트

#107 주문 생성 테스트 코드 추가
  src/main/java/com/palpal/dealightbe/domain/order/application/OrderService.java
  src/main/java/com/palpal/dealightbe/global/error/ErrorCode.java
  src/test/java/com/palpal/dealightbe/domain/order/application/OrderServiceIntegrationTest.java
  src/test/java/com/palpal/dealightbe/domain/order/application/OrderServiceTest.java
Labels: 💡 feature, 두번째 스프린트

#110 hotfix: 중복된 Image DTO 삭제
  src/main/java/com/palpal/dealightbe/domain/image/application/dto/response/ImageRes.java
  src/main/java/com/palpal/dealightbe/domain/image/dto/request/ImageUploadReq.java
  src/main/java/com/palpal/dealightbe/domain/image/dto/response/ImageRes.java
  src/main/java/com/palpal/dealightbe/domain/member/application/MemberService.java
  src/main/java/com/palpal/dealightbe/domain/member/presentation/MemberController.java
  src/test/java/com/palpal/dealightbe/domain/member/application/MemberServiceTest.java
  src/test/java/com/palpal/dealightbe/domain/member/presentation/MemberControllerTest.java
Labels: 🚨 hotfix

#119 AOP 적용
  src/docs/asciidoc/Order.adoc
  src/docs/asciidoc/Review.adoc
  src/main/java/com/palpal/dealightbe/domain/order/presentation/OrderController.java
  src/test/java/com/palpal/dealightbe/domain/order/presentation/OrderControllerTest.java
  src/test/java/com/palpal/dealightbe/domain/review/presentation/ReviewControllerTest.java
Labels: 🛠️ refactoring, 세번째 스프린트

#116 회원가입 완료 고객의 업체 등록 유무 확인 API
  src/docs/asciidoc/Store.adoc
  src/main/java/com/palpal/dealightbe/domain/store/application/StoreService.java
  src/main/java/com/palpal/dealightbe/domain/store/application/dto/response/StoreByMemberRes.java
  src/main/java/com/palpal/dealightbe/domain/store/domain/StoreRepository.java
  src/main/java/com/palpal/dealightbe/domain/store/presentation/StoreController.java
  src/test/java/com/palpal/dealightbe/domain/store/application/StoreServiceTest.java
  src/test/java/com/palpal/dealightbe/domain/store/presentation/StoreControllerTest.java
Labels: 💡 feature, 세번째 스프린트

#120 고객이 리뷰 작성시 선택 가능한 항목들 반환
  src/docs/asciidoc/Review.adoc
  src/main/java/com/palpal/dealightbe/domain/review/application/dto/response/ReviewContentRes.java
  src/main/java/com/palpal/dealightbe/domain/review/presentation/ReviewController.java
  src/test/java/com/palpal/dealightbe/domain/review/presentation/ReviewControllerTest.java
Labels: 💡 feature, 세번째 스프린트

#121 상품 이미지 수정 기능
  src/docs/asciidoc/Item.adoc
  src/main/java/com/palpal/dealightbe/domain/item/application/ItemService.java
  src/main/java/com/palpal/dealightbe/domain/item/presentation/ItemController.java
  src/test/java/com/palpal/dealightbe/domain/item/application/ItemServiceTest.java
  src/test/java/com/palpal/dealightbe/domain/item/presentation/ItemControllerTest.java
Labels: 💡 feature, 세번째 스프린트

#124 상품 이미지 삭제 기능
  src/docs/asciidoc/Item.adoc
  src/main/java/com/palpal/dealightbe/config/JpaConfig.java
  src/main/java/com/palpal/dealightbe/domain/item/application/ItemService.java
  src/test/java/com/palpal/dealightbe/domain/item/presentation/ItemControllerTest.java
Labels: 💡 feature, 세번째 스프린트

#130 hotfix: 상품 목록 조회 시 페이지 번호 수정
  src/main/java/com/palpal/dealightbe/config/JpaConfig.java
  src/main/java/com/palpal/dealightbe/domain/item/presentation/ItemController.java
Labels: 🚨 hotfix, 세번째 스프린트

#132 hotfix: 상품 Response Dto 리팩토링
  src/docs/asciidoc/Item.adoc
  src/main/java/com/palpal/dealightbe/domain/item/application/dto/response/ItemRes.java
  src/main/java/com/palpal/dealightbe/domain/item/application/dto/response/ItemsRes.java
  src/main/resources/static/docs/Item.html
  src/test/java/com/palpal/dealightbe/domain/item/application/ItemServiceTest.java
  src/test/java/com/palpal/dealightbe/domain/item/presentation/ItemControllerTest.java
Labels: 🚨 hotfix, 세번째 스프린트

#127 인증 관련 AOP 적용(멤버)
  src/main/java/com/palpal/dealightbe/domain/member/application/MemberService.java
  src/main/java/com/palpal/dealightbe/domain/member/domain/MemberRole.java
  src/main/java/com/palpal/dealightbe/domain/member/presentation/MemberController.java
  src/test/java/com/palpal/dealightbe/domain/member/application/MemberServiceTest.java
  src/test/java/com/palpal/dealightbe/domain/member/presentation/MemberControllerTest.java
Labels: 🛠️ refactoring, 세번째 스프린트

#139 상품 AOP 적용
  src/docs/asciidoc/Item.adoc
  src/main/java/com/palpal/dealightbe/domain/item/application/ItemService.java
  src/main/java/com/palpal/dealightbe/domain/item/domain/ItemRepository.java
  src/main/java/com/palpal/dealightbe/domain/item/presentation/ItemController.java
  src/main/resources/static/docs/Item.html
  src/test/java/com/palpal/dealightbe/domain/item/application/ItemServiceTest.java
  src/test/java/com/palpal/dealightbe/domain/item/presentation/ItemControllerTest.java
Labels: 🛠️ refactoring, 세번째 스프린트

#150 페이징 - 페이지 1부터 시작하도록 수정
  src/main/java/com/palpal/dealightbe/domain/order/presentation/OrderController.java
Labels: 💡 feature, 네번째 스프린트

#153 멤버 AOP 명세 관련 코드 수정
  src/docs/asciidoc/Member.adoc
  src/main/resources/static/docs/Member.html
Labels: 네번째 스프린트

#151 Notification 도메인 생성
  src/main/java/com/palpal/dealightbe/domain/notification/domain/Notification.java
  src/main/java/com/palpal/dealightbe/domain/notification/domain/NotificationType.java
Labels: 네번째 스프린트

#155 배포서버에서 카카오 로그인 이후 Redirect URL 접근시 404 에러가 뜨는 오류
  .github/workflows/script-for-test.yml
  src/main/java/com/palpal/dealightbe/config/SecurityConfig.java
  src/main/java/com/palpal/dealightbe/domain/auth/presentation/CustomOAuth2AuthenticationSuccessHandler.java
  src/main/java/com/palpal/dealightbe/domain/image/infrastructure/S3ImageService.java
Labels: 🐞 bug, 🛜 infra, 네번째 스프린트

#160 업체 조회(검색) API 구현 (컨트롤러 테스트 전)
  src/main/java/com/palpal/dealightbe/domain/address/application/AddressService.java
  src/main/java/com/palpal/dealightbe/domain/item/application/ItemService.java
  src/main/java/com/palpal/dealightbe/domain/item/domain/ItemSortType.java
  src/main/java/com/palpal/dealightbe/domain/store/application/StoreService.java
  src/main/java/com/palpal/dealightbe/domain/store/application/dto/request/StoreCreateReq.java
  src/main/java/com/palpal/dealightbe/domain/store/application/dto/response/StoreInfoSliceRes.java
  src/main/java/com/palpal/dealightbe/domain/store/application/dto/response/StoresInfoSliceRes.java
  src/main/java/com/palpal/dealightbe/domain/store/domain/Store.java
  src/main/java/com/palpal/dealightbe/domain/store/domain/StoreRepository.java
  src/main/java/com/palpal/dealightbe/domain/store/presentation/StoreController.java
  src/main/java/com/palpal/dealightbe/global/SearchSortType.java
  src/main/java/com/palpal/dealightbe/global/error/ErrorCode.java
  src/test/java/com/palpal/dealightbe/domain/address/application/AddressServiceTest.java
  src/test/java/com/palpal/dealightbe/domain/store/application/StoreServiceTest.java
  src/test/java/com/palpal/dealightbe/domain/store/domain/StoreRepositoryTest.java
Labels: 💡 feature, 네번째 스프린트

#158 업체의 상품 목록 조회 API (고객 시점) 구현
  src/docs/asciidoc/Item.adoc
  src/main/java/com/palpal/dealightbe/domain/item/application/ItemService.java
  src/main/java/com/palpal/dealightbe/domain/item/domain/Item.java
  src/main/java/com/palpal/dealightbe/domain/item/presentation/ItemController.java
  src/main/resources/static/docs/Item.html
  src/test/java/com/palpal/dealightbe/domain/item/application/ItemServiceTest.java
  src/test/java/com/palpal/dealightbe/domain/item/presentation/ItemControllerTest.java
Labels: 💡 feature, 네번째 스프린트

#164 상품 목록 페이징 Slice 처리
  src/main/java/com/palpal/dealightbe/domain/item/application/ItemService.java
  src/main/java/com/palpal/dealightbe/domain/item/application/dto/response/ItemsRes.java
  src/main/java/com/palpal/dealightbe/domain/item/domain/ItemRepository.java
  src/main/java/com/palpal/dealightbe/domain/item/domain/ItemRepositoryCustom.java
  src/main/java/com/palpal/dealightbe/domain/item/infrastructure/ItemRepositoryImpl.java
  src/test/java/com/palpal/dealightbe/domain/item/application/ItemServiceTest.java
  src/test/java/com/palpal/dealightbe/domain/item/presentation/ItemControllerTest.java
Labels: 🚨 hotfix, 네번째 스프린트

#169 업체 검색 컨트롤러 테스트 및 RestDocs
  src/docs/asciidoc/Store.adoc
  src/main/java/com/palpal/dealightbe/domain/store/application/StoreService.java
  src/test/java/com/palpal/dealightbe/domain/store/application/StoreServiceTest.java
  src/test/java/com/palpal/dealightbe/domain/store/domain/StoreRepositoryTest.java
  src/test/java/com/palpal/dealightbe/domain/store/presentation/StoreControllerTest.java
Labels: 💡 feature, 네번째 스프린트

#166 SSE 알림기능(subscribe)
  src/main/java/com/palpal/dealightbe/domain/notification/application/NotificationService.java
  src/main/java/com/palpal/dealightbe/domain/notification/domain/EmitterRepository.java
  src/main/java/com/palpal/dealightbe/domain/notification/domain/Notification.java
  src/main/java/com/palpal/dealightbe/domain/notification/domain/NotificationRepository.java
  src/main/java/com/palpal/dealightbe/domain/notification/presentation/NotificationController.java
  src/main/java/com/palpal/dealightbe/domain/order/application/OrderService.java
  src/main/java/com/palpal/dealightbe/domain/order/domain/OrderStatus.java
  src/main/java/com/palpal/dealightbe/global/error/ErrorCode.java
Labels: 💡 feature, 네번째 스프린트

#167 장바구니 조회 API 구현
  src/docs/asciidoc/Cart.adoc
  src/main/java/com/palpal/dealightbe/domain/cart/application/CartService.java
  src/main/java/com/palpal/dealightbe/domain/cart/application/dto/response/CartsRes.java
  src/main/java/com/palpal/dealightbe/domain/cart/domain/Cart.java
  src/main/java/com/palpal/dealightbe/domain/cart/domain/CartAdditionType.java
  src/main/java/com/palpal/dealightbe/domain/cart/presentation/CartController.java
  src/main/java/com/palpal/dealightbe/global/error/ErrorCode.java
  src/main/resources/static/docs/Cart.html
  src/test/java/com/palpal/dealightbe/domain/cart/presentation/CartControllerTest.java
Labels: 💡 feature, 네번째 스프린트

#173 장바구니 수정 API 구현
  src/docs/asciidoc/Cart.adoc
  src/docs/asciidoc/Item.adoc
  src/main/java/com/palpal/dealightbe/domain/cart/application/CartService.java
  src/main/java/com/palpal/dealightbe/domain/cart/application/dto/request/CartsReq.java
  src/main/java/com/palpal/dealightbe/domain/cart/application/dto/response/CartRes.java
  src/main/java/com/palpal/dealightbe/domain/cart/domain/Cart.java
  src/main/java/com/palpal/dealightbe/domain/cart/presentation/CartController.java
  src/main/java/com/palpal/dealightbe/domain/item/application/ItemService.java
  src/main/java/com/palpal/dealightbe/domain/item/presentation/ItemController.java
  src/main/java/com/palpal/dealightbe/domain/store/application/StoreService.java
  src/main/java/com/palpal/dealightbe/global/ListSortType.java
  src/main/java/com/palpal/dealightbe/global/error/ErrorCode.java
  src/main/resources/static/docs/Cart.html
  src/main/resources/static/docs/Item.html
  src/test/java/com/palpal/dealightbe/domain/cart/presentation/CartControllerTest.java
  src/test/java/com/palpal/dealightbe/domain/item/presentation/ItemControllerTest.java
Labels: 💡 feature, 네번째 스프린트

#174 rest docs - 실패 테스트 추가(주문/리뷰)
  src/docs/asciidoc/Order.adoc
  src/docs/asciidoc/Review.adoc
  src/main/java/com/palpal/dealightbe/domain/order/application/OrderService.java
  src/main/java/com/palpal/dealightbe/global/error/ErrorCode.java
  src/test/java/com/palpal/dealightbe/domain/order/application/OrderServiceIntegrationTest.java
  src/test/java/com/palpal/dealightbe/domain/order/domain/OrderRepositoryTest.java
  src/test/java/com/palpal/dealightbe/domain/order/presentation/OrderControllerTest.java
  src/test/java/com/palpal/dealightbe/domain/review/presentation/ReviewControllerTest.java
Labels: 🗂️ document, 네번째 스프린트

#175 장바구니 삭제 API 구현
  src/docs/asciidoc/Cart.adoc
  src/main/java/com/palpal/dealightbe/domain/cart/application/CartService.java
  src/main/java/com/palpal/dealightbe/domain/cart/presentation/CartController.java
  src/test/java/com/palpal/dealightbe/domain/cart/presentation/CartControllerTest.java
  src/test/java/com/palpal/dealightbe/domain/item/application/ItemServiceTest.java
Labels: 💡 feature, 네번째 스프린트

#178 업체 영업 종료 시 상품 삭제 기능 추가
  src/main/java/com/palpal/dealightbe/domain/cart/domain/Cart.java
  src/main/java/com/palpal/dealightbe/domain/item/domain/Item.java
  src/main/java/com/palpal/dealightbe/domain/item/domain/ItemRepository.java
  src/main/java/com/palpal/dealightbe/domain/store/application/StoreService.java
  src/test/java/com/palpal/dealightbe/domain/cart/presentation/CartControllerTest.java
  src/test/java/com/palpal/dealightbe/domain/item/application/ItemServiceTest.java
  src/test/java/com/palpal/dealightbe/domain/item/presentation/ItemControllerTest.java
Labels: 💡 feature, 네번째 스프린트

#183 Member 프로필 조회 수정
  src/main/java/com/palpal/dealightbe/domain/member/application/dto/response/MemberProfileRes.java
  src/test/java/com/palpal/dealightbe/domain/member/presentation/MemberControllerTest.java
Labels: 🛠️ refactoring, 네번째 스프린트

#185 hotfix: Item.adoc 수정
  src/docs/asciidoc/Item.adoc
Labels: 🚨 hotfix, 네번째 스프린트

#186 hotfix: MemberServiceTest 수정
  src/test/java/com/palpal/dealightbe/domain/member/application/MemberServiceTest.java
Labels: 🚨 hotfix, 네번째 스프린트

#188 hotfix: Item, Cart 명세 수정
  src/docs/asciidoc/Cart.adoc
  src/docs/asciidoc/Item.adoc
  src/test/java/com/palpal/dealightbe/domain/cart/presentation/CartControllerTest.java
  src/test/java/com/palpal/dealightbe/domain/item/presentation/ItemControllerTest.java
Labels: 🚨 hotfix, 네번째 스프린트

#197 hotfix: Member 프로필 반환 DTO 필드 수정
  src/main/java/com/palpal/dealightbe/domain/member/application/dto/response/MemberProfileRes.java
Labels: 🚨 hotfix, 네번째 스프린트

#189 업체 정보 추가등록시 Role 변경해서 토큰 재발급
  src/docs/asciidoc/Auth.adoc
  src/main/java/com/palpal/dealightbe/domain/auth/application/AuthService.java
  src/main/java/com/palpal/dealightbe/domain/auth/presentation/AuthController.java
  src/main/java/com/palpal/dealightbe/domain/member/domain/Member.java
  src/main/java/com/palpal/dealightbe/global/error/GlobalExceptionHandler.java
  src/test/java/com/palpal/dealightbe/domain/auth/application/AuthServiceTest.java
  src/test/java/com/palpal/dealightbe/domain/auth/application/OAuth2AuthorizationServiceTest.java
  src/test/java/com/palpal/dealightbe/domain/auth/presentation/AuthControllerTest.java
Labels: 💡 feature, 네번째 스프린트

#196 추가 요구사항: 닉네임 중복확인 API 구현
  src/docs/asciidoc/Auth.adoc
  src/main/java/com/palpal/dealightbe/config/SecurityConfig.java
  src/main/java/com/palpal/dealightbe/domain/auth/application/AuthService.java
  src/main/java/com/palpal/dealightbe/domain/auth/application/dto/request/MemberNickNameCheckReq.java
  src/main/java/com/palpal/dealightbe/domain/auth/application/dto/request/MemberSignupAuthReq.java
  src/main/java/com/palpal/dealightbe/domain/auth/presentation/AuthController.java
  src/main/java/com/palpal/dealightbe/domain/member/domain/Member.java
  src/main/java/com/palpal/dealightbe/domain/member/domain/MemberRepository.java
  src/main/java/com/palpal/dealightbe/global/error/ErrorCode.java
  src/test/java/com/palpal/dealightbe/domain/auth/application/AuthServiceTest.java
  src/test/java/com/palpal/dealightbe/domain/auth/presentation/AuthControllerTest.java
Labels: 💡 feature, 네번째 스프린트

#194 업체 검색 쿼리문 QueryDSL로 리팩토링
  src/docs/asciidoc/Store.adoc
  src/main/java/com/palpal/dealightbe/domain/item/application/ItemService.java
  src/main/java/com/palpal/dealightbe/domain/item/infrastructure/ItemRepositoryImpl.java
  src/main/java/com/palpal/dealightbe/domain/store/application/StoreService.java
  src/main/java/com/palpal/dealightbe/domain/store/domain/StoreRepository.java
  src/main/java/com/palpal/dealightbe/domain/store/domain/StoreRepositoryCustom.java
  src/main/java/com/palpal/dealightbe/domain/store/domain/StoreRepositoryImpl.java
  src/main/java/com/palpal/dealightbe/domain/store/domain/StoreStatus.java
  src/main/java/com/palpal/dealightbe/domain/store/presentation/StoreController.java
  src/main/java/com/palpal/dealightbe/global/ListSortType.java
  src/test/java/com/palpal/dealightbe/domain/store/application/StoreServiceTest.java
  src/test/java/com/palpal/dealightbe/domain/store/domain/StoreRepositoryTest.java
  src/test/java/com/palpal/dealightbe/domain/store/presentation/StoreControllerTest.java
Labels: 🆙 performance, 🛠️ refactoring, 네번째 스프린트

#200 hotfix: ItemRepositoryTest 테스트 코드 수정
  src/test/java/com/palpal/dealightbe/domain/item/domain/ItemRepositoryTest.java
Labels: 🚨 hotfix, 다섯번째 스프린트

#201 hotfix: Member 프로필 반환 DTO 필드 수정 및 Member.adoc 수정
  src/docs/asciidoc/Member.adoc
  src/main/java/com/palpal/dealightbe/domain/member/application/dto/response/MemberProfileRes.java
  src/main/resources/static/docs/Member.html
  src/test/java/com/palpal/dealightbe/domain/member/presentation/MemberControllerTest.java
Labels: 🚨 hotfix

#203 ItemController 목록 조회 기능 엔드 포인트 수정
  src/docs/asciidoc/Item.adoc
  src/main/java/com/palpal/dealightbe/domain/item/presentation/ItemController.java
  src/test/java/com/palpal/dealightbe/domain/item/presentation/ItemControllerTest.java
Labels: 🚨 hotfix, 다섯번째 스프린트

#205 hotfix: Item.adoc 수정
  src/docs/asciidoc/Item.adoc
  src/test/java/com/palpal/dealightbe/domain/item/presentation/ItemControllerTest.java
Labels: 🚨 hotfix, 다섯번째 스프린트

#207 hotfix: Item.adoc 수정
  src/docs/asciidoc/Item.adoc
Labels: 🚨 hotfix, 다섯번째 스프린트

#211 docs : 명세 형식 및 오타 수정
  src/docs/asciidoc/Order.adoc
  src/docs/asciidoc/Review.adoc
  src/test/java/com/palpal/dealightbe/domain/review/presentation/ReviewControllerTest.java
Labels: 🗂️ document, 🚨 hotfix

#212 hotfix : 테스트 내의 mocking 오류 수정
  src/test/java/com/palpal/dealightbe/domain/review/presentation/ReviewControllerTest.java
Labels: 🚨 hotfix

#214 업체 등록시 이미 업체를 보유하고 있는지 유효성 검사 추가
  src/docs/asciidoc/Store.adoc
  src/main/java/com/palpal/dealightbe/domain/store/application/StoreService.java
  src/main/java/com/palpal/dealightbe/global/error/ErrorCode.java
  src/test/java/com/palpal/dealightbe/domain/store/application/StoreServiceTest.java
  src/test/java/com/palpal/dealightbe/domain/store/presentation/StoreControllerTest.java
Labels: 🐞 bug, 💡 feature, 다섯번째 스프린트

#216 스프링 액츄에이터, 메트릭, 프로메테우스, 그라파나 도입
  build.gradle
  src/main/java/com/palpal/dealightbe/domain/auth/domain/Jwt.java
  src/main/java/com/palpal/dealightbe/domain/auth/filter/JwtAuthenticationFilter.java
  src/main/java/com/palpal/dealightbe/domain/auth/presentation/AuthController.java
  src/main/resources/application-actuator.yml
  src/main/resources/application.yml
  src/test/java/com/palpal/dealightbe/domain/auth/presentation/AuthControllerTest.java
Labels: 🛜 infra, 다섯번째 스프린트

#218 hotfix: ItemController lastId 제거, dto 네이밍 변경
  src/docs/asciidoc/Item.adoc
  src/main/java/com/palpal/dealightbe/domain/item/application/ItemService.java
  src/main/java/com/palpal/dealightbe/domain/item/application/dto/request/ItemReq.java
  src/main/java/com/palpal/dealightbe/domain/item/presentation/ItemController.java
  src/test/java/com/palpal/dealightbe/domain/item/application/ItemServiceTest.java
  src/test/java/com/palpal/dealightbe/domain/item/presentation/ItemControllerTest.java
Labels: 🚨 hotfix, 다섯번째 스프린트

#220 hotfix: Item 필드, Item Response 수정
  src/main/java/com/palpal/dealightbe/domain/item/application/dto/request/ItemReq.java
  src/main/java/com/palpal/dealightbe/domain/item/application/dto/response/ItemRes.java
  src/main/java/com/palpal/dealightbe/domain/item/domain/Item.java
  src/test/java/com/palpal/dealightbe/domain/cart/presentation/CartControllerTest.java
  src/test/java/com/palpal/dealightbe/domain/item/application/ItemServiceTest.java
  src/test/java/com/palpal/dealightbe/domain/item/domain/ItemRepositoryTest.java
  src/test/java/com/palpal/dealightbe/domain/item/presentation/ItemControllerTest.java
  src/test/java/com/palpal/dealightbe/domain/order/application/OrderServiceIntegrationTest.java
  src/test/java/com/palpal/dealightbe/domain/store/application/StoreServiceTest.java
Labels: 🚨 hotfix, 다섯번째 스프린트

#223 hotfix: Member 프로필 주소 업데이트 로직 수정
  src/main/java/com/palpal/dealightbe/domain/member/domain/Member.java
Labels: 🐞 bug, 🚨 hotfix

#224 업체 검색 QueryDSL 불필요한 정렬 조건 삭제
  src/main/java/com/palpal/dealightbe/domain/store/domain/StoreRepositoryImpl.java
Labels: 🐞 bug, 다섯번째 스프린트

#225 DayOffs 필드 LazyLoading 수정
  src/main/java/com/palpal/dealightbe/domain/store/application/dto/response/StoreCreateRes.java
  src/main/java/com/palpal/dealightbe/domain/store/application/dto/response/StoreInfoRes.java
  src/test/java/com/palpal/dealightbe/domain/store/application/StoreServiceTest.java
  src/test/java/com/palpal/dealightbe/domain/store/presentation/StoreControllerTest.java
Labels: 🐞 bug, 다섯번째 스프린트

#221 Sonar Cloud세팅, JaCoCo세팅 및 PR, CI시 연동 설정
  .github/workflows/script-dev.yml
  .github/workflows/sonarcloud.yml
  build.gradle
  lombok.config
  src/main/resources/application-actuator.yml
Labels: 🛜 infra, 다섯번째 스프린트

#227 SSE 알림 기능(읽음처리 및 캐시삭제) 구현
  src/main/java/com/palpal/dealightbe/domain/auth/application/AuthService.java
  src/main/java/com/palpal/dealightbe/domain/auth/presentation/AuthController.java
  src/main/java/com/palpal/dealightbe/domain/member/application/MemberService.java
  src/main/java/com/palpal/dealightbe/domain/notification/application/NotificationService.java
  src/main/java/com/palpal/dealightbe/domain/notification/application/dto/response/NotificationsRes.java
  src/main/java/com/palpal/dealightbe/domain/notification/domain/EmitterRepository.java
  src/main/java/com/palpal/dealightbe/domain/notification/domain/NotificationRepository.java
  src/main/java/com/palpal/dealightbe/domain/notification/presentation/NotificationController.java
  src/main/java/com/palpal/dealightbe/domain/notification/util/EventIdUtil.java
  src/main/java/com/palpal/dealightbe/domain/notification/util/NotificationUtil.java
Labels: 💡 feature, 다섯번째 스프린트

#228 상품 목록 조회 기능 QueryDSL 적용
  src/docs/asciidoc/Cart.adoc
  src/docs/asciidoc/Item.adoc
  src/main/java/com/palpal/dealightbe/domain/item/application/ItemService.java
  src/main/java/com/palpal/dealightbe/domain/item/domain/ItemRepository.java
  src/main/java/com/palpal/dealightbe/domain/item/domain/ItemRepositoryCustom.java
  src/main/java/com/palpal/dealightbe/domain/item/domain/ItemRepositoryImpl.java
  src/main/java/com/palpal/dealightbe/domain/item/infrastructure/ItemRepositoryImpl.java
  src/test/java/com/palpal/dealightbe/domain/cart/presentation/CartControllerTest.java
  src/test/java/com/palpal/dealightbe/domain/item/application/ItemServiceTest.java
  src/test/java/com/palpal/dealightbe/domain/item/domain/ItemRepositoryTest.java
Labels: 🛠️ refactoring, 다섯번째 스프린트

#234 업체 마이페이지 API 수정 및 업체 상세 페이지(고객 사용) API 추가
  src/docs/asciidoc/Store.adoc
  src/main/java/com/palpal/dealightbe/domain/store/application/StoreService.java
  src/main/java/com/palpal/dealightbe/domain/store/presentation/StoreController.java
  src/test/java/com/palpal/dealightbe/domain/store/application/StoreServiceTest.java
  src/test/java/com/palpal/dealightbe/domain/store/presentation/StoreControllerTest.java
Labels: 🐞 bug, 🚨 hotfix, 🛠️ refactoring, 다섯번째 스프린트

#237 hotfix: 장바구니 수정 기능 최신화 로직 추가
  src/main/java/com/palpal/dealightbe/domain/cart/application/CartService.java
Labels: 🚨 hotfix, 다섯번째 스프린트

#240 feat : 주문 다건 조회 버그 수정
  src/main/java/com/palpal/dealightbe/domain/order/domain/Order.java
Labels: 🐞 bug, 🚨 hotfix

#241 hotfix: 장바구니 담기 기능 최신화 로직 추가
  src/docs/asciidoc/Cart.adoc
  src/main/java/com/palpal/dealightbe/domain/cart/application/CartService.java
  src/test/java/com/palpal/dealightbe/domain/cart/presentation/CartControllerTest.java
Labels: 🚨 hotfix, 다섯번째 스프린트

#243 feat : 주문 다건 조회 버그 수정
  src/main/java/com/palpal/dealightbe/domain/order/domain/OrderRepository.java
Labels: 🐞 bug, 다섯번째 스프린트

#246 리뷰 API 버그 수정
  src/docs/asciidoc/Review.adoc
  src/main/java/com/palpal/dealightbe/domain/order/domain/Order.java
  src/main/java/com/palpal/dealightbe/domain/review/application/ReviewService.java
  src/main/java/com/palpal/dealightbe/global/error/ErrorCode.java
  src/test/java/com/palpal/dealightbe/domain/review/application/ReviewServiceIntegrationTest.java
  src/test/java/com/palpal/dealightbe/domain/review/presentation/ReviewControllerTest.java
Labels: 🐞 bug

#247 주문 취소시 재고 증가
  src/main/java/com/palpal/dealightbe/domain/item/domain/Item.java
  src/main/java/com/palpal/dealightbe/domain/order/application/OrderService.java
  src/test/java/com/palpal/dealightbe/domain/order/application/OrderServiceIntegrationTest.java
Labels: 🐞 bug, 🚨 hotfix

#250 hotfix: CartService 중복 코드 제거
  src/main/java/com/palpal/dealightbe/domain/cart/application/CartService.java
Labels: 🚨 hotfix, 🛠️ refactoring, 다섯번째 스프린트

#251 SSE 알림 스케줄링 적용
  src/main/java/com/palpal/dealightbe/config/SchedulerConfig.java
  src/main/java/com/palpal/dealightbe/domain/notification/application/NotificationService.java
  src/main/java/com/palpal/dealightbe/domain/notification/domain/Notification.java
  src/main/java/com/palpal/dealightbe/domain/notification/domain/NotificationRepository.java
  src/main/java/com/palpal/dealightbe/domain/order/application/OrderService.java
Labels: 💡 feature, 다섯번째 스프린트

#248 리뷰 작성 API - 중복 있는 경우
  src/main/java/com/palpal/dealightbe/domain/review/application/dto/request/ReviewCreateReq.java
  src/test/java/com/palpal/dealightbe/domain/review/application/ReviewServiceIntegrationTest.java
Labels: 💡 feature, 다섯번째 스프린트

#255 업체 영업 종료 시 장바구니 상품 만료 삭제 로직 추가
  src/main/java/com/palpal/dealightbe/domain/cart/application/CartService.java
Labels: 🐞 bug, 🚨 hotfix, 다섯번째 스프린트

#257 hotfix: 장바구니 기능 버그 수정
  src/docs/asciidoc/Cart.adoc
  src/docs/asciidoc/Item.adoc
  src/main/java/com/palpal/dealightbe/domain/cart/application/CartService.java
  src/main/java/com/palpal/dealightbe/domain/cart/domain/CartRepository.java
  src/main/java/com/palpal/dealightbe/global/error/ErrorCode.java
  src/test/java/com/palpal/dealightbe/domain/cart/presentation/CartControllerTest.java
Labels: 🐞 bug, 🚨 hotfix, 다섯번째 스프린트

#261 hotfix: CartService 코드 리팩토링
  src/main/java/com/palpal/dealightbe/domain/cart/application/CartService.java
Labels: 🚨 hotfix, 🛠️ refactoring, 다섯번째 스프린트

#264 ItemRepository 조회 쿼리 페치 조인 적용
  src/main/java/com/palpal/dealightbe/domain/item/domain/ItemRepository.java
  src/test/java/com/palpal/dealightbe/domain/order/application/OrderServiceIntegrationTest.java
Labels: 💡 feature, 다섯번째 스프린트

#265 ProviderIdAop 예외처리 문제 해결, profile에서 변경된 address 조회문제 해결, 회원탈퇴시 store의 item도 모두 삭제하도록 변경
  build.gradle
  src/main/java/com/palpal/dealightbe/config/SecurityConfig.java
  src/main/java/com/palpal/dealightbe/domain/address/domain/Address.java
  src/main/java/com/palpal/dealightbe/domain/auth/application/AuthService.java
  src/main/java/com/palpal/dealightbe/domain/auth/application/CustomAuthenticationEntryPoint.java
  src/main/java/com/palpal/dealightbe/domain/auth/presentation/AuthController.java
  src/main/java/com/palpal/dealightbe/domain/item/application/ItemService.java
  src/main/java/com/palpal/dealightbe/domain/item/domain/Item.java
  src/main/java/com/palpal/dealightbe/domain/member/domain/Member.java
  src/main/java/com/palpal/dealightbe/domain/store/application/StoreService.java
  src/main/java/com/palpal/dealightbe/domain/store/domain/Store.java
  src/main/java/com/palpal/dealightbe/global/aop/ProviderIdAop.java
  src/main/resources/static/docs/Auth.html
  src/main/resources/static/docs/Cart.html
  src/main/resources/static/docs/Item.html
  src/main/resources/static/docs/Member.html
  src/main/resources/static/docs/Order.html
  src/main/resources/static/docs/Review.html
  src/main/resources/static/docs/Store.html
  src/test/java/com/palpal/dealightbe/domain/auth/application/AuthServiceTest.java
Labels: 🐞 bug, 다섯번째 스프린트

#268 SSE 알림 내 Redis Pub/Sub 적용
  src/main/java/com/palpal/dealightbe/config/RedisConfig.java
  src/main/java/com/palpal/dealightbe/domain/notification/application/NotificationService.java
  src/main/java/com/palpal/dealightbe/domain/notification/application/dto/response/NotificationRes.java
  src/main/java/com/palpal/dealightbe/domain/notification/domain/Notification.java
  src/main/java/com/palpal/dealightbe/domain/notification/util/NotificationUtil.java
  src/main/java/com/palpal/dealightbe/global/error/ErrorCode.java
Labels: 💡 feature, 다섯번째 스프린트

#277 hotfix: 상품 할인가&원가 조건 수정
  src/main/java/com/palpal/dealightbe/domain/item/domain/Item.java
  src/main/java/com/palpal/dealightbe/global/error/ErrorCode.java
  src/test/java/com/palpal/dealightbe/domain/cart/presentation/CartControllerTest.java
  src/test/java/com/palpal/dealightbe/domain/item/presentation/ItemControllerTest.java
Labels: 🚨 hotfix, 다섯번째 스프린트

#271 SSE 알림 내 인증 AOP 적용
  src/main/java/com/palpal/dealightbe/domain/member/domain/MemberRepository.java
  src/main/java/com/palpal/dealightbe/domain/notification/application/NotificationService.java
  src/main/java/com/palpal/dealightbe/domain/notification/application/dto/NotificationUserInfo.java
  src/main/java/com/palpal/dealightbe/domain/notification/application/dto/response/NotificationsRes.java
  src/main/java/com/palpal/dealightbe/domain/notification/domain/NotificationRepository.java
  src/main/java/com/palpal/dealightbe/domain/notification/presentation/NotificationController.java
  src/main/java/com/palpal/dealightbe/domain/order/application/OrderService.java
Labels: 💡 feature, 다섯번째 스프린트

#276 상품 주문 동시성 문제 해결
  build.gradle
  src/main/java/com/palpal/dealightbe/DealightBeApplication.java
  src/main/java/com/palpal/dealightbe/config/RedisConfig.java
  src/main/java/com/palpal/dealightbe/domain/item/application/ItemService.java
  src/main/java/com/palpal/dealightbe/domain/item/domain/Item.java
  src/main/java/com/palpal/dealightbe/domain/item/domain/ItemRepository.java
  src/main/java/com/palpal/dealightbe/domain/item/domain/ItemRepositoryCustom.java
  src/main/java/com/palpal/dealightbe/domain/item/domain/ItemRepositoryImpl.java
  src/main/java/com/palpal/dealightbe/domain/order/application/OrderService.java
  src/main/java/com/palpal/dealightbe/domain/order/application/dto/request/OrderProductReq.java
  src/main/java/com/palpal/dealightbe/domain/order/application/dto/response/OrderRes.java
  src/main/java/com/palpal/dealightbe/domain/order/domain/Order.java
  src/main/java/com/palpal/dealightbe/domain/order/domain/OrderItem.java
  src/test/java/com/palpal/dealightbe/domain/order/application/OrderServiceIntegrationTest.java
  src/test/java/com/palpal/dealightbe/domain/order/domain/OrderTest.java
Labels: 💡 feature

#284 hotfix: 장바구니 에러 메시지 변경
  src/main/java/com/palpal/dealightbe/domain/cart/application/CartService.java
  src/main/java/com/palpal/dealightbe/global/error/ErrorCode.java
  src/test/java/com/palpal/dealightbe/domain/cart/presentation/CartControllerTest.java
Labels: 🛠️ refactoring, 다섯번째 스프린트

#285 상품 삭제 오류 해결
  src/main/java/com/palpal/dealightbe/domain/item/domain/Item.java
  src/main/java/com/palpal/dealightbe/domain/item/domain/ItemRepository.java
  src/main/java/com/palpal/dealightbe/domain/order/application/OrderService.java
Labels: 🐞 bug, 💡 feature, 🚨 hotfix, 다섯번째 스프린트
