Repository Team-PalPalHae-Dealight/Team-PalPalHae-Dealight-BE, pull requests merged in 2023-10, with the labels that each got.

#10 docs: 이슈 템플릿 수정
  .github/ISSUE_TEMPLATE/dealight-be-issue-template.md
Labels: 🗂️ document

#30 hotfix: GlobalExceptionHandler에 누락된 예외 추가
  src/main/java/com/palpal/dealightbe/global/error/GlobalExceptionHandler.java
Labels: 🚨 hotfix

#33 hotfix: 엔티티 연관관계 수정
  src/main/java/com/palpal/dealightbe/domain/member/domain/Member.java
  src/main/java/com/palpal/dealightbe/domain/oAuth/domain/OAuth.java
  src/main/java/com/palpal/dealightbe/domain/store/domain/Store.java
Labels: 첫번째 스프린트, 🚨 hotfix

#36 업체 등록 API 구현
  src/docs/asciidoc/Store.adoc
  src/main/java/com/palpal/dealightbe/domain/address/application/AddressService.java
  src/main/java/com/palpal/dealightbe/domain/address/application/dto/response/AddressRes.java
  src/main/java/com/palpal/dealightbe/domain/address/domain/Address.java
  src/main/java/com/palpal/dealightbe/domain/address/domain/AddressRepository.java
  src/main/java/com/palpal/dealightbe/domain/member/domain/MemberRepository.java
  src/main/java/com/palpal/dealightbe/domain/store/application/StoreService.java
  src/main/java/com/palpal/dealightbe/domain/store/application/dto/request/StoreCreateReq.java
  src/main/java/com/palpal/dealightbe/domain/store/application/dto/response/StoreCreateRes.java
  src/main/java/com/palpal/dealightbe/domain/store/domain/DayOff.java
  src/main/java/com/palpal/dealightbe/domain/store/domain/Store.java
  src/main/java/com/palpal/dealightbe/domain/store/domain/StoreRepository.java
  src/main/java/com/palpal/dealightbe/domain/store/presentation/StoreController.java
  src/main/java/com/palpal/dealightbe/global/error/ErrorCode.java
  src/test/java/com/palpal/dealightbe/domain/address/application/AddressServiceTest.java
  src/test/java/com/palpal/dealightbe/domain/store/application/StoreServiceTest.java
  src/test/java/com/palpal/dealightbe/domain/store/presentation/StoreControllerTest.java
Labels: 첫번째 스프린트, 💡 feature

#38 branch내 시큐리티 관련 주석 처리
  build.gradle
Labels: 🚨 hotfix

#39 상품 등록 API 구현
  src/docs/asciidoc/item.adoc
  src/main/java/com/palpal/dealightbe/domain/item/application/ItemService.java
  src/main/java/com/palpal/dealightbe/domain/item/application/dto/request/ItemReq.java
  src/main/java/com/palpal/dealightbe/domain/item/application/dto/response/ItemRes.java
  src/main/java/com/palpal/dealightbe/domain/item/domain/Item.java
  src/main/java/com/palpal/dealightbe/domain/item/domain/ItemRepository.java
  src/main/java/com/palpal/dealightbe/domain/item/presentation/ItemController.java
  src/main/java/com/palpal/dealightbe/domain/store/domain/StoreRepository.java
  src/main/java/com/palpal/dealightbe/global/error/ErrorCode.java
  src/test/java/com/palpal/dealightbe/domain/item/application/ItemServiceTest.java
  src/test/java/com/palpal/dealightbe/domain/item/presentation/ItemControllerTest.java
Labels: 첫번째 스프린트, 💡 feature

#40 이미지 도메인 생성
  build.gradle
  src/main/java/com/palpal/dealightbe/config/S3Config.java
  src/main/java/com/palpal/dealightbe/domain/image/ImageService.java
  src/main/java/com/palpal/dealightbe/domain/image/exception/ImageIOException.java
  src/main/java/com/palpal/dealightbe/domain/image/exception/InvalidFileTypeException.java
  src/main/java/com/palpal/dealightbe/domain/image/infrastructure/S3ImageService.java
  src/main/java/com/palpal/dealightbe/global/error/ErrorCode.java
Labels: 첫번째 스프린트, 💡 feature

#42 업체 마이페이지 조회 API 및 RestDocs 구현
  src/docs/asciidoc/Store.adoc
  src/main/java/com/palpal/dealightbe/domain/member/domain/Member.java
  src/main/java/com/palpal/dealightbe/domain/member/domain/MemberRole.java
  src/main/java/com/palpal/dealightbe/domain/member/domain/Role.java
  src/main/java/com/palpal/dealightbe/domain/member/domain/RoleType.java
  src/main/java/com/palpal/dealightbe/domain/store/application/StoreService.java
  src/main/java/com/palpal/dealightbe/domain/store/application/dto/response/StoreInfoRes.java
  src/main/java/com/palpal/dealightbe/domain/store/domain/Store.java
  src/main/java/com/palpal/dealightbe/domain/store/presentation/StoreController.java
  src/main/java/com/palpal/dealightbe/global/error/ErrorCode.java
  src/test/java/com/palpal/dealightbe/domain/store/application/StoreServiceTest.java
  src/test/java/com/palpal/dealightbe/domain/store/presentation/StoreControllerTest.java
Labels: 첫번째 스프린트, 💡 feature

#43 상품 수정 API 구현
  src/docs/asciidoc/Item.adoc
  src/main/java/com/palpal/dealightbe/domain/item/application/ItemService.java
  src/main/java/com/palpal/dealightbe/domain/item/domain/Item.java
  src/main/java/com/palpal/dealightbe/domain/item/presentation/ItemController.java
  src/test/java/com/palpal/dealightbe/domain/item/application/ItemServiceTest.java
  src/test/java/com/palpal/dealightbe/domain/item/presentation/ItemControllerTest.java
Labels: 첫번째 스프린트, 💡 feature

#44 고객 정보 조회 API 구현
  src/docs/asciidoc/member.adoc
  src/main/java/com/palpal/dealightbe/domain/member/application/MemberService.java
  src/main/java/com/palpal/dealightbe/domain/member/application/dto/response/MemberProfileRes.java
  src/main/java/com/palpal/dealightbe/domain/member/domain/Member.java
  src/main/java/com/palpal/dealightbe/domain/member/presentation/MemberController.java
  src/test/java/com/palpal/dealightbe/domain/member/application/MemberServiceTest.java
  src/test/java/com/palpal/dealightbe/domain/member/presentation/MemberControllerTest.java
Labels: 첫번째 스프린트, 💡 feature

#45 카카오 소셜 로그인 토큰 발급 및 서비스 토큰 발급
  build.gradle
  src/main/java/com/palpal/dealightbe/config/JwtConfig.java
  src/main/java/com/palpal/dealightbe/config/SecurityConfig.java
  src/main/java/com/palpal/dealightbe/domain/auth/application/AuthService.java
  src/main/java/com/palpal/dealightbe/domain/auth/application/JoinRequireRes.java
  src/main/java/com/palpal/dealightbe/domain/auth/application/LoginRes.java
  src/main/java/com/palpal/dealightbe/domain/auth/domain/Jwt.java
  src/main/java/com/palpal/dealightbe/domain/auth/infra/AuthRepository.java
  src/main/java/com/palpal/dealightbe/domain/auth/infra/HttpCookieAuth2AuthorizationRequestRepository.java
  src/main/java/com/palpal/dealightbe/domain/auth/presentation/CustomOAuth2AuthenticationSuccessHandler.java
  src/main/java/com/palpal/dealightbe/domain/member/domain/Member.java
  src/main/java/com/palpal/dealightbe/domain/member/domain/MemberRole.java
  src/main/java/com/palpal/dealightbe/domain/member/domain/Role.java
  src/main/resources/logback.xml
  src/test/java/com/palpal/dealightbe/domain/auth/application/AuthServiceTest.java
Labels: 첫번째 스프린트, 💡 feature

#53 hotfix: Controller 테스트 코드 excludeAutoConfiguration 설정 추가
  src/test/java/com/palpal/dealightbe/domain/item/presentation/ItemControllerTest.java
  src/test/java/com/palpal/dealightbe/domain/member/presentation/MemberControllerTest.java
  src/test/java/com/palpal/dealightbe/domain/store/presentation/StoreControllerTest.java
Labels: 첫번째 스프린트, 🚨 hotfix

#48 업체 마이페이지 정보 수정 API 및 RestDocs
  src/docs/asciidoc/Store.adoc
  src/main/java/com/palpal/dealightbe/domain/store/application/StoreService.java
  src/main/java/com/palpal/dealightbe/domain/store/application/dto/request/StoreUpdateReq.java
  src/main/java/com/palpal/dealightbe/domain/store/domain/Store.java
  src/main/java/com/palpal/dealightbe/domain/store/presentation/StoreController.java
  src/test/java/com/palpal/dealightbe/domain/store/application/StoreServiceTest.java
  src/test/java/com/palpal/dealightbe/domain/store/presentation/StoreControllerTest.java
Labels: 첫번째 스프린트, 💡 feature

#56 hotfix: ItemControllerTest, ItemServiceTest 테스트 코드 수정
  src/test/java/com/palpal/dealightbe/domain/item/application/ItemServiceTest.java
  src/test/java/com/palpal/dealightbe/domain/item/presentation/ItemControllerTest.java
Labels: 🐞 bug, 🚨 hotfix
