Repository Team-PalPalHae-Dealight/Team-PalPalHae-Dealight-BE, pull requests merged in 2023-12, with the labels that each got.

#294 hotfix: 멤버 프로필 수정 닉네임 중복검사
  src/main/java/com/palpal/dealightbe/domain/member/application/MemberService.java
  src/main/java/com/palpal/dealightbe/domain/member/application/dto/request/MemberUpdateReq.java
  src/main/java/com/palpal/dealightbe/domain/member/application/dto/response/MemberUpdateRes.java
  src/main/java/com/palpal/dealightbe/domain/member/presentation/MemberController.java
  src/test/java/com/palpal/dealightbe/domain/member/application/MemberServiceTest.java
  src/test/java/com/palpal/dealightbe/domain/member/presentation/MemberControllerTest.java
Labels: 🚨 hotfix

#293 테스트코드 추가 및 개선
  src/main/java/com/palpal/dealightbe/domain/order/application/OrderService.java
  src/main/java/com/palpal/dealightbe/domain/order/domain/Order.java
  src/test/java/com/palpal/dealightbe/common/ControllerTest.java
  src/test/java/com/palpal/dealightbe/common/IntegrationTest.java
  src/test/java/com/palpal/dealightbe/domain/auth/application/AuthServiceTest.java
  src/test/java/com/palpal/dealightbe/domain/auth/presentation/AuthControllerTest.java
  src/test/java/com/palpal/dealightbe/domain/cart/presentation/CartControllerTest.java
  src/test/java/com/palpal/dealightbe/domain/item/presentation/ItemControllerTest.java
  src/test/java/com/palpal/dealightbe/domain/member/presentation/MemberControllerTest.java
  src/test/java/com/palpal/dealightbe/domain/order/application/OrderServiceIntegrationTest.java
  src/test/java/com/palpal/dealightbe/domain/order/application/OrderServiceTest.java
  src/test/java/com/palpal/dealightbe/domain/order/domain/OrderTest.java
  src/test/java/com/palpal/dealightbe/domain/order/presentation/OrderControllerTest.java
  src/test/java/com/palpal/dealightbe/domain/review/application/ReviewServiceIntegrationTest.java
  src/test/java/com/palpal/dealightbe/domain/review/presentation/ReviewControllerTest.java
  src/test/java/com/palpal/dealightbe/domain/store/presentation/StoreControllerTest.java
Labels: 🆙 performance, 🛠️ refactoring, 다섯번째 스프린트

#297 Member 인덱스 적용 및 updateProfile 수정
  src/main/java/com/palpal/dealightbe/domain/member/application/MemberService.java
  src/main/java/com/palpal/dealightbe/domain/member/domain/Member.java
Labels: 🚨 hotfix, 🆙 performance, 다섯번째 스프린트

#302 상품 목록 조회 기능 커버링 인덱스 적용
  src/main/java/com/palpal/dealightbe/domain/item/domain/ItemRepositoryImpl.java
  src/main/resources/data.sql
Labels: 🆙 performance, 🛠️ refactoring, 다섯번째 스프린트

#306 장바구니 담기, 수정 기능 요청 횟수 제한
  build.gradle
  src/docs/asciidoc/Cart.adoc
  src/main/java/com/palpal/dealightbe/config/BucketConfig.java
  src/main/java/com/palpal/dealightbe/domain/cart/application/CartService.java
  src/main/java/com/palpal/dealightbe/global/error/ErrorCode.java
  src/main/java/com/palpal/dealightbe/global/error/GlobalExceptionHandler.java
  src/main/java/com/palpal/dealightbe/global/error/exception/ExcessiveRequestException.java
  src/main/resources/data.sql
  src/test/java/com/palpal/dealightbe/domain/cart/presentation/CartControllerTest.java
Labels: 💡 feature, 🆙 performance, 다섯번째 스프린트
